spring:
  profiles:
    active: ${SPRING_PROFILE:dev}
  application:
    name: cotador-service
server:
  port: 8080
  servlet:
    context-path: /api
springdoc:
  packages-to-scan: com.creditas.cotador.api.v1.controller