spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: bruno.cavalcanti@foop.com.br
    password: zqio djta kbld xjro
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
app:
  timezone: America/Sao_Paulo
  emailFrom: bruno.cavalcanti@foop.com.br